import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#E6D5A7',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 16,
    minHeight: 60,
  },
  headerButton: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: 'rgba(42, 17, 40, 0.05)',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#2A1128',
    letterSpacing: 1,
  },
  headerRightContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  profileCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
    borderRadius: 24,
    padding: 24,
    marginTop: 20,
    borderWidth: 1,
    borderColor: 'rgba(42, 17, 40, 0.1)',
  },
  avatarContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#2A1128',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    shadowColor: '#2A1128',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 4,
  },
  emailText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#2A1128',
  },
  roleText: {
    fontSize: 14,
    color: '#2A1128',
    opacity: 0.6,
    marginTop: 4,
    fontWeight: '500',
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginTop: 24,
    borderTopWidth: 1,
    borderTopColor: 'rgba(42, 17, 40, 0.08)',
    paddingTop: 20,
  },
  statCol: {
    flex: 1,
    alignItems: 'center',
  },
  statDivider: {
    width: 1,
    backgroundColor: 'rgba(42, 17, 40, 0.08)',
    height: '100%',
  },
  statVal: {
    fontSize: 24,
    fontWeight: '800',
    color: '#2A1128',
  },
  statLabel: {
    fontSize: 12,
    color: '#2A1128',
    opacity: 0.7,
    marginTop: 4,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2A1128',
    marginTop: 32,
    marginBottom: 16,
  },
  badgesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  badgeCard: {
    width: '48%',
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    alignItems: 'center',
    borderWidth: 1.5,
    position: 'relative',
  },
  unlockedBadge: {
    borderColor: 'rgba(42, 17, 40, 0.2)',
    backgroundColor: 'rgba(255, 255, 255, 0.65)',
  },
  lockedBadge: {
    borderColor: 'rgba(42, 17, 40, 0.05)',
    opacity: 0.6,
  },
  badgeIconContainer: {
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  badgeTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#2A1128',
    textAlign: 'center',
  },
  badgeDesc: {
    fontSize: 11,
    color: '#2A1128',
    opacity: 0.6,
    textAlign: 'center',
    marginTop: 4,
    lineHeight: 14,
  },
  lockIndicator: {
    position: 'absolute',
    top: 8,
    right: 8,
  },
  badgeProgress: {
    fontSize: 10,
    color: '#2A1128',
    opacity: 0.7,
    fontWeight: '700',
    marginTop: 6,
    backgroundColor: 'rgba(42, 17, 40, 0.06)',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
  },
  emptyTasksCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 16,
    padding: 24,
    alignItems: 'center',
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: 'rgba(42, 17, 40, 0.2)',
  },
  emptyTasksText: {
    fontSize: 14,
    color: '#2A1128',
    opacity: 0.6,
    textAlign: 'center',
    marginTop: 8,
  },
  taskItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
    padding: 16,
    borderRadius: 16,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: 'rgba(42, 17, 40, 0.05)',
  },
  taskTextContainer: {
    flex: 1,
    marginLeft: 12,
  },
  taskTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#2A1128',
  },
  taskMeta: {
    fontSize: 12,
    color: '#2A1128',
    opacity: 0.5,
    marginTop: 2,
  },
  evidenceIndicator: {
    padding: 6,
    backgroundColor: 'rgba(4, 211, 97, 0.1)',
    borderRadius: 20,
    marginLeft: 8,
  },
  settingsCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(42, 17, 40, 0.1)',
  },
  settingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  settingLabel: {
    fontSize: 15,
    fontWeight: '700',
    color: '#2A1128',
  },
  themeToggleContainer: {
    flexDirection: 'row',
    backgroundColor: 'rgba(42, 17, 40, 0.08)',
    borderRadius: 12,
    padding: 4,
  },
  themeButton: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 8,
  },
  activeThemeButton: {
    backgroundColor: '#2A1128',
  },
  themeButtonText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#2A1128',
  },
  activeThemeButtonText: {
    color: '#E6D5A7',
  },
});
